name: Laravel Code Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, php-cs-fixer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHP Code Linter
        run: vendor/bin/phpcs --standard=PSR12 app/ routes/ database/
